apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-hdlee
  labels:
    app: frontend-hdlee
spec:
  selector:
    matchLabels:
      app: frontend-hdlee
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-hdlee
    spec:
      containers:
        - name: frontend-hdlee
          image: hdlee/front-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
