apiVersion: v1
kind: Service
metadata:
  name: frontend-hdlee
  labels:
    name: frontend-hdlee
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend-hdlee
  type: NodePort
